SEGINW_CATEGORIES = {'seginw_Helmet-Head': ['Helmet'], 
                    'seginw_Line-Contour': ['line-structure'], 
                    'seginw_Elephants': ['elephant'], 
                    'seginw_Hand-Metal': ['hand', 'metal'], 
                    'seginw_Watermelon': ['watermelon'], 
                    'seginw_House-Parts': ['aluminium door', 'aluminium window', 'cellar window', 'mint cond roof', 'plaster', 'plastic door', 'plastic window', 'plate fascade', 'wooden door', 'wooden fascade', 'wooden window', 'worn cond roof'], 
                    'seginw_HouseHold-Items': ['bottle', 'mouse', 'perfume', 'phone'], 
                    'seginw_Strawberry': ['R_strawberry', 'people'], 
                    'seginw_WareHouse-Box': ['box', 'dmg box', 'label'], 
                    'seginw_Fruits': ['apple', 'lemon', 'orange', 'pear', 'strawberry'], 
                    'seginw_Nutterfly-Squireel': ['butterfly', 'squirrel'], 
                    'seginw_Hand': ['Hand-Segmentation', 'hand'], 
                    'seginw_Garbage': ['bin', 'garbage', 'pavement', 'road'], 
                    'seginw_Chicken': ['chicken'], 
                    'seginw_Rail': ['rail'], 
                    'seginw_Airplane-Parts': ['Airplane', 'Body', 'Cockpit', 'Engine', 'Wing'], 
                    'seginw_Face-Mask': ['Mask'], 
                    'seginw_Brain-Tumor': ['tumor'], 
                    'seginw_Poles': ['poles'], 
                    'seginw_Car-Parts': ['back_bumper', 'back_door', 'back_glass', 'back_light', 'front_bumper', 'front_door', 'front_glass', 'front_light', 'hood'], 
                    'seginw_Electric-Shaver': ['caorau'], 
                    'seginw_Bottles': ['bottle', 'can', 'label'], 
                    'seginw_Toolkits': ['Allen-key', 'block', 'gasket', 'plier', 'prism', 'screw', 'screwdriver', 'wrench'], 
                    'seginw_Trash': ['Aluminium foil', 'Cigarette', 'Clear plastic bottle', 'Corrugated carton', 'Disposable plastic cup', 'Drink Can', 'Egg Carton', 'Foam cup', 'Food Can', 'Garbage bag', 'Glass bottle', 'Glass cup', 'Metal bottle cap', 'Other carton', 'Other plastic bottle', 'Paper cup', 'Plastic bag - wrapper', 'Plastic bottle cap', 'Plastic lid', 'Plastic straw', 'Pop tab', 'Styrofoam piece'], 
                    'seginw_Salmon-Fillet': ['Salmon_fillet'], 
                    'seginw_Puppies': ['puppy'], 
                    'seginw_Tablets': ['tablets'], 
                    'seginw_Cable': ['cable'], 
                    'seginw_Fire': ['fire'], 
                    'seginw_Phones': ['phone'], 
                    'seginw_Cows': ['cow'], 
                    'seginw_Ginger-Garlic': ['garlic', 'ginger']
                    }